CREATE TABLE `produk` (
  `idProduk` VARCHAR(255) NOT NULL,
  `idToko` VARCHAR(255) DEFAULT NULL,
  `idKategori` VARCHAR(255) DEFAULT NULL,
  `idDetail` VARCHAR(255) DEFAULT NULL,
  `addBy` VARCHAR(255) DEFAULT NULL,
  `addTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idProduk`)
) ENGINE=INNODB DEFAULT CHARSET=latin1;
